name: 打包应用并上传腾讯云

on:
    push:
        branches:
            - master

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: windows-latest
        steps:
            # 获取源码
            - name: 迁出代码
              # 使用action库  actions/checkout获取源码
              uses: actions/checkout@master

            # 安装Node10
            - name: 安装node.js
              # 使用action库  actions/setup-node安装node
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: "14.X"

            # 安装依赖
            - name: 安装依赖
              run: npm install

            # 打包
            - name: 打包
              run: npm run vercel-build
              env: 
                DATABASE_URL: ${{ secrets.DATABASE_URL }}
                NODE_ENV: ${{ secrets.NODE_ENV }}
                TOKEN_SECRET_KEY: ${{ secrets.TOKEN_SECRET_KEY }}

            # 上传阿里云
            - name: 发布到腾讯云
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                 server: ${{ secrets.REMOTE_HOST }}
                 username: ${{ secrets.USERNAME }}
                 ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
                 port: 22
                 local_path: "./dist/*"
                 remote_path: ${{ secrets.TARGET }}